# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: 'extract translations'
      run: npx jambo extract-translations --globs '*/**/*{.hbs,.js}' '!**/node_modules' $IGNORED_FOLDERS --output $OUTPUT_FILE
      env:
        IGNORED_FOLDERS: '!{commands,hbshelpers,patches,postupgrade,static,tests,test-site,translations}/**'
        OUTPUT_FILE: 'translations/messages.pot'
    - run: |
        cd translations
        for po_file in *.po
          do msgcmp $po_file messages.pot
        done

